# -*- coding: utf-8 -*-
"""np_array_ops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1keVMEZMOYFR7H77GUFXKkX4cSpnplfki
"""

# operations on numpy array

import numpy as np

# arange function to print odd no.s between 1 and 10 
arr = np.arange(1,10,2)
arr

# unction returns number spaces evenly w.r.t interval. 
x1 = np.linspace(0, 2, 15)
x1

# create np array where all elements are by default 1
a = np.ones([3, 3], dtype = int)
a

# create np array where all elements are by default 0
b = np.zeros([3, 3], dtype = int)
b

# create empty np array 
e = np.empty([2, 2], dtype = int)
e

# create 2d np array with digonal elemnts specified
c = np.eye(5, dtype = int)
c

# to genarate 12 samples between 0.1 and 1.5
x2 = np.logspace(0.1, 1.5, 12) 
x2

# create np array where all elements are by default random
r = np.random.rand(5, 5)
r

# reshape np array in other dimensions
arr2 = np.arange(8).reshape(2, 4)
arr2

# genarate random integer betwen given range
r_int = np.random.randint(0,10)
r_int

# function creates an array of specified shape and fills it with random values as per standard normal distribution
r2 = np.random.randn(3, 4)
r2